course_links = {
    'python': 'https://www.youtube.com/watch?v=_uQrJ0TkZlc',
    'sql': 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
    'excel': 'https://www.youtube.com/watch?v=VLmPuyqLaZg',
    'statistics': 'https://www.youtube.com/watch?v=xxpc-HPKN28',
    'pandas': 'https://www.youtube.com/watch?v=vmEHCJofslg',
    'tableau': 'https://www.youtube.com/watch?v=1yGqIuQUb-Y',
    'html': 'https://www.youtube.com/watch?v=pQN-pnXPaVg',
    'css': 'https://www.youtube.com/watch?v=yfoY53QXEnI',
    'javascript': 'https://www.youtube.com/watch?v=PkZNo7MFNFg',
    'react': 'https://www.youtube.com/watch?v=DLX62G4lc44',
    'django': 'https://www.youtube.com/watch?v=F5mRW0jo-U4',
    'git': 'https://www.youtube.com/watch?v=USjZcfj8yxE',
    'web development': 'https://www.youtube.com/watch?v=3JluqTojuME',
    'machine learning': 'https://www.youtube.com/watch?v=Gv9_4yMHFhI',
    'deep learning': 'https://www.youtube.com/watch?v=aircAruvnKk',
    'scikit-learn': 'https://www.youtube.com/watch?v=0Lt9w-BxKFQ',
    'nlp': 'https://www.youtube.com/watch?v=8rXD5-xhemo',
    'cyber security': 'https://www.youtube.com/watch?v=inWWhr5tnEA',
    'networking': 'https://www.youtube.com/watch?v=qiQR5rTSshw',
    'linux': 'https://www.youtube.com/watch?v=ROjZy1WbCIA',
    'aws': 'https://www.youtube.com/watch?v=ulprqHHWlng',
    'azure': 'https://www.youtube.com/watch?v=BegR8I2o6lA',
    'cloud computing': 'https://www.youtube.com/watch?v=2LaAJq1lB1Q',
    'docker': 'https://www.youtube.com/watch?v=fqMOX6JJhGo',
    'kubernetes': 'https://www.youtube.com/watch?v=X48VuDVv0do',
    'terraform': 'https://www.youtube.com/watch?v=7xngnjfIlK4',
    'ci/cd': 'https://www.youtube.com/watch?v=scEDHsr3APg',
    'jenkins': 'https://www.youtube.com/watch?v=Fxm3r2LIr8A',
    'ansible': 'https://www.youtube.com/watch?v=wgQ3rH5Y0uw',
    'typescript': 'https://www.youtube.com/watch?v=30LWjhZzg50',
    'bootstrap': 'https://www.youtube.com/watch?v=-qfEOE4vtxE',
    'figma': 'https://www.youtube.com/watch?v=FTFaQWZBqQ8',
    'kotlin': 'https://www.youtube.com/watch?v=F9UC9DY-vIU',
    'android studio': 'https://www.youtube.com/watch?v=BBWyXo-3JGQ',
    'swift': 'https://www.youtube.com/watch?v=comQ1-x2a1Q',
    'xcode': 'https://www.youtube.com/watch?v=09TeUXjzpKs',
    'salesforce': 'https://www.youtube.com/watch?v=3ajVwYjfGQw',
    'openai': 'https://www.youtube.com/watch?v=rcTQ-xp6Iaw',
    'langchain': 'https://www.youtube.com/watch?v=7wXq6J2hgNQ',
    'unity': 'https://www.youtube.com/watch?v=IlKaB1etrik',
    'c#': 'https://www.youtube.com/watch?v=GhQdlIFylQ8',
    'solidity': 'https://www.youtube.com/watch?v=gyMwXuJrbJQ',
    'ethereum': 'https://www.youtube.com/watch?v=ipwxYa-F1uY',
    'postgresql': 'https://www.youtube.com/watch?v=qw--VYLpxG4',
    'oracle': 'https://www.youtube.com/watch?v=WDJacg0NuLo',
    'agile': 'https://www.youtube.com/watch?v=Z9QbYZh1YXY',
    'scrum': 'https://www.youtube.com/watch?v=9TycLR0TqFA',
    'jira': 'https://www.youtube.com/watch?v=fI0eZzgoDMs',
    'blender': 'https://www.youtube.com/watch?v=TPrnSACiTJ4',
    'r': 'https://www.youtube.com/watch?v=_V8eKsto3Ug',
    'genomics': 'https://www.youtube.com/watch?v=1fiJupfbSpg',
    'bioinformatics': 'https://www.youtube.com/watch?v=I1Lw5JFEijs',
    'sequence analysis': 'https://www.youtube.com/watch?v=4a0FbQdH3dY',
}

def suggest_courses(missing_skills):
    suggestions = {}
    for skill in missing_skills:
        if skill in course_links:
            suggestions[skill] = course_links[skill]
    return suggestions

